name: Simple action
author: Serve Laurijssen

inputs:
  who_to_greet: 
    description: "who to greet"
    required: true
    default: "World"
outputs:
  time:
    description: "time of greeting"
    
runs:
  using: "node20"
  main: index.js
  #pre: 'setup.js'
  #pre-if: runner.os == 'linux'
  #post: 'cleanup.js'
  #post-if: runner.os == 'linux'
  
