name: github client tests
run-name: ${{ github.actor }} is testing gh client
on:
  workflow_dispatch:
  
jobs:
  test-github-client:
    runs-on: ubuntu-latest
    steps:
    - name: check out
      uses: actions/checkout@v4
    - name: install gh
      run: |
        sudo apt update
        sudo apt install gh
    - name: Generate a token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
#        owner: ${{ github.repository_owner }}
#        repositories: dotnet.api
        app-id: ${{ secrets.SECRETS_APP_ID }}
        private-key: ${{ secrets.SECRETS_APP_PRIVATE_KEY }}     
    - name: repos
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}   
      run: gh repo list
    - name: variable
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
      run: gh variable set TEST --body "4321"
